name: clinica_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logoClinica.png
    - lib/assets/logoWas.jpg
    - lib/assets/whatsapp.png
    - lib/assets/letrasClinica.png
    - lib/assets/letrasClinica2.png
    - lib/assets/huella.jpg
    - lib/assets/huella.png
    - lib/assets/icon_cesta.png
    - lib/assets/icon_citas.png
    - lib/assets/icon_mascotas.png
    - lib/assets/icon_pedirCita.png
    - lib/assets/icon_tienda.png