name: clinica_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  image_picker: ^1.0.7
  http: ^1.2.1
  shared_preferences: ^2.2.2 # O la última versión disponible

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logoClinica.png
    - lib/assets/logoWas.jpg
    - lib/assets/whatsapp.png
    - lib/assets/letrasClinica.png
    - lib/assets/letrasClinica2.png
    - lib/assets/huella.jpg
    - lib/assets/huella.png
    - lib/assets/icon_cesta.png
    - lib/assets/icon_citas.png
    - lib/assets/icon_mascotas.png
    - lib/assets/icon_pedirCita.png
    - lib/assets/icon_tienda.png
    - lib/assets/icon_editarUsuario.png
    - lib/assets/icon_ajustesUsuario.png
    - lib/assets/icon_ayudaUsuario.png
    - lib/assets/icon_cerrarSesion.png
    - lib/assets/icon_citasUsuario.png
    - lib/assets/icon_favoritosUsuario.png
    - lib/assets/icon_historialCitasUsuario.png
    - lib/assets/icon_mascotasUsuario.png
    - lib/assets/icon_notificacionUsuario.png
    - lib/assets/icon_pagosUsuario.png